name: Starter Action
description: just a Starter

inputs:
  actiontype: 
    description: the wished action
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@4  
    - name: notification
      if: ${{ inputs.actiontype == 'notification'}}
      uses: ./.github/workflows/starter.yml
#      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
#      shell: bash
#      env:
#        GITHUB_ACTION_PATH: ${{ github.action_path }}
