name: Starter Action
description: just a Starter

inputs:
  action_path:
    description: should contain the github action_path
    required: true
  actiontype: 
    description: the wished action
    required: true

runs:
  using: "composite"
  steps:
    - name: delegatestuff
      if: ${{ inputs.actiontype == 'notification'}}
      uses: "${{ inputs.actionpath }}/../.github/workflows/notify.yml"
      with:
        actiontype: ${{ inputs.actiontype }}
      shell: bash       
    - name: defaultstuff
      if: ${{ inputs.actiontype != 'notification'}}
      run: echo "The calling application did not want a notification"
      shell: bash


