name: Starter Action
description: just a Starter

inputs:
  actiontype: 
    description: the wished action
    required: true

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}  
    - name: delegatestuff
      if: ${{ inputs.actiontype == 'notification'}}
      #uses: "${{ github.action_path }}/.github/workflows/notify.yml"
      #uses: "AWPPT/baseworkflows/.github/workflows/notify.yml@main"
#      with:
#        actiontype: ${{ inputs.actiontype }}
      run: echo "action path ${{ github.action_path }}"
      shell: bash       
    - name: defaultstuff
      if: ${{ inputs.actiontype != 'notification'}}
      run: echo "The calling application did not want a notification"
      shell: bash


