name: Notify Teams

on:
    workflow_call:
        inputs:
            repositoryname:
                required: true
                type: string
            releasename:
                required: true
                type: string

jobs:
    notifyteams:
        name: Notify Teams
        runs-on: ubuntu-latest
        steps:
          - name: Run find-and-replace to replace <REPLACE_REPOSITORY>
            uses: mad9000/actions-find-and-replace-string@5
            id: findandreplace
            with:
                source: ${{ vars.POST_RELEASE_TEAMS_MESSAGE }}
                find: '<REPLACE_REPOSITORY>'
                replace: ${{ inputs.repositoryname }}
          - name: Run find-and-replace to replace <REPLACE_RELEASE>
            uses: mad9000/actions-find-and-replace-string@5
            id: findandreplace2
            with:
                source: ${{ steps.findandreplace.outputs.value }}
                find: '<REPLACE_RELEASE>'
                replace: ${{ inputs.releasename }}
          - name: message stage
#            uses: fjogeleit/http-request-action@v1
#            env:
#                strBasePost: ${{ steps.findandreplace2.outputs.value }}
#            with:
#                url: ${{ vars.MS_TEAMS_WEBHOOK_URL }}
#                method: 'POST'
#                preventFailureOnNoResponse: true
#                customHeaders: '{"Content-Type": "application/json"}'
#                data: ${{ env.strBasePost }}
