name: Starter Action

on: workflow_dispatch

jobs:
  collectversion:
    runs-on: ubuntu-latest
    outputs:
        releasevalue: ${{ steps.releasescript.outputs.actual_release }}
        description: contains then the actual release provided by test.sh
    steps:
        - uses: actions/checkout@v4    
        - name: Run script file
          id: releasescript
          run: |
             chmod +x ./scripts/test.sh
             ./scripts/test.sh
          shell: bash
  logversion:
    runs-on: ubuntu-latest
    needs: [collectversion]
    steps:
        - name: Group of log lines
          id: debuglog
          run: |
            echo "::group::My title"
            echo "${{ toJSON(needs.collectversion.outputs) }}"
            echo "${{ needs.collectversion.outputs.releasevalue }}"            
            echo "::endgroup::"
  startmessage:
    needs: [collectversion]  
    uses: ./.github/workflows/notifyteams.yml
    with:
      repositoryname: ${{ github.event.repository.name }}
      releasename: ${{ needs.collectversion.outputs.releasevalue }}     
                    
